config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('diario/', include('diario.urls')),
    path('protocolo/', include('protocolo.urls')),
    path("to-c", include("clients.urls")),
    path('', include('mentha.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

protocolo/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "protocolo"

urlpatterns = [
                path('', views.protocolos_view, name="protocols"),
                path('incrementar/<int:part_id>/<int:participant_id>', views.incrementar, name='incrementar'), #estou só a fazer testes!
                path('dashboard', views.dashboard_view, name="dashboard"),
                path('popup',views.popup_view,name = 'popup'),
                path('', views.menu_protocolo_view, name="app-view"),
                #path('risk',views.risk_form_view,name="risk"),
                path('teste', views.teste, name='teste'),
                path('participant/<int:protocol_id>', views.participant_risk_view, name='participant_risk'),
                path('protocol-participants/<int:protocol_id>', views.protocol_participants_view,
                    name="protocol-participants"),
                path('participants', views.participants_view, name="participants"),
                path('dashboard-content', views.dashboard_content_view, name="dashboard-content"),
                path('atualizar-tabela', views.parte_do_utilizador_add_view, name = "atualizar-tabela"),

                path('parts/<int:protocol_id>/<int:patient_id>', views.parts_view, name="parts"),
                path('parts/<int:protocol_id>/<int:patient_id>/<str:cuidador>', views.parts_view, name="parts"),

                path('parte', views.parte_view, name = "parte"),

                path('areas/<int:protocol_id>/<int:part_id>/<int:patient_id>', views.areas_view, name="areas"),
                path('areas/<int:protocol_id>/<int:part_id>/<int:patient_id>/<str:is_cuidador>', views.areas_view, name="areas"),

                path('instruments/<int:protocol_id>/<int:part_id>/<int:area_id>/<int:patient_id>', views.instruments_view, name="instruments"),
                path('instruments/<int:protocol_id>/<int:part_id>/<int:area_id>/<int:patient_id>/<str:is_cuidador>', views.instruments_view, name="instruments"),

                #path('risco', views.risco_view, name="risco"),
                path('dimension/<int:protocol_id>/<int:part_id>/<int:area_id>/<int:instrument_id>/<int:patient_id>',
                    views.dimensions_view, name="dimensions"),
                path('dimension/<int:protocol_id>/<int:part_id>/<int:area_id>/<int:instrument_id>/<int:patient_id>/<str:is_cuidador>',
                    views.dimensions_view, name="dimensions"),

                path('section/<int:protocol_id>/<int:part_id>/<int:area_id>/<int:instrument_id>/<int:dimension_id>/<int:patient_id>',
                    views.sections_view, name="sections"),
                path('section/<int:protocol_id>/<int:part_id>/<int:area_id>/<int:instrument_id>/<int:dimension_id>/<int:patient_id>/<str:is_cuidador>',
                    views.sections_view, name="sections"),

                path('question/<int:protocol_id>/<int:part_id>/<int:area_id>/<int:instrument_id>/<int:dimension_id>/<int:section_id>/<int:patient_id>',
                    views.question_view, name="question"),
                path('question/<int:protocol_id>/<int:part_id>/<int:area_id>/<int:instrument_id>/<int:dimension_id>/<int:section_id>/<int:patient_id>/<str:is_cuidador>',
                    views.question_view, name="question"),

                path('report2/<int:resolution_id>', views.report2, name="report2"),
                path('nova_pagina_risk_report/',views.nova_pagina_risk_report, name='nova_pagina_risk_report'),
                path('report/<int:resolution_id>', views.report_view, name="report"),
                path('report_risk',views.report_risk,name="report_risk"), #estou só a fazer testes! A ver se este funciona
                path('login', views.login_view, name="login"),
                path('logout', views.logout_view, name="logout"),
                path('profile/<int:participant_id>/', views.profile_view, name="participant"),
                path('delete_button/<int:partedoutilizador_id>/<int:participant_id>', views.delete_button, name='delete_button'),
                path('participantes_registo/',views.registo_view,name="participantes_registo"),
                path('avaliadores_registo/',views.avaliadores_registo_view,name="avaliadores_registo"),
                path('participant-overview/<int:participant_id>/', views.patient_overview_view,
                    name="participant-overview"),
                path('participante_update/<str:participante_id>', views.participante_update,
                    name='participante_update'),
                path('cuidador_update/<str:cuidador_id>', views.cuidador_update,
                         name='cuidador_update'),
                path(
                    'gds-overview/<int:protocol_id>/<int:part_id>/<int:area_id>/<int:instrument_id>/<int:patient_id>',
                    views.gds_overview_view,
                    name="gds-overview"),
                path('colaboradores', views.colaboradores_view, name="colaboradores"),
                path('profile_cuidador/<int:cuidador_id>/', views.profile_cuidador_view, name="profile_cuidador"),
                path('exportar_risk/', views.export_risk_to_csv, name='export_risk_to_csv'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

protocolo/views.py
from django.contrib.auth import logout
import io
from platform import python_compiler
from django.http import HttpResponseRedirect, JsonResponse, FileResponse
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from matplotlib import pyplot as plt
from .models import Protocol, Part, Area, Instrument, Dimension, Section, Question, Resolution, Answer, PossibleAnswer, Risk
from django.contrib.auth.models import User
from django.contrib.auth.models import Group as DjangoGroup
from django.urls import reverse
from .functions import *
from .forms import *
from diario.models import *
import json
import os
import csv


# Other Imports
import plotly.graph_objects as go
import plotly
import pandas as pd
import time
import hashlib
import random
from PIL import Image, ImageDraw, ImageFont
from docx.shared import Pt


from bs4 import BeautifulSoup

import numpy as np
import plotly.offline as py_offline


# word Imports to PDF
from docx import Document
from docx.shared import Inches
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from docx.shared import RGBColor
from docx.oxml.ns import nsdecls
from docx.oxml import parse_xml


import os


# Create your views here.
def remove_empty_keys_from_post(post_data):
    return {key: value for key, value in post_data.items() if value != ''}


def inserir():
    a1 = PossibleAnswer.objects.get(pk=310)
    a2 = PossibleAnswer.objects.get(pk=311)
    a3 = PossibleAnswer.objects.get(pk=312)
    a4 = PossibleAnswer.objects.get(pk=313)
    a5 = PossibleAnswer.objects.get(pk=314)
    a6 = PossibleAnswer.objects.get(pk=315)

    qorder = 1
    qtype = 3
    section = Section.objects.get(pk=116)
    text_list = [
        "De quantos familiares se sente próximo de tal forma que possa ligar-lhes para pedir ajuda?",
        "Com quantos familiares se sente à vontade para falar sobre assuntos pessoais?",
        "Quantos amigos vê ou fala pelo menos uma vez por mês?",
        "De quantos amigos se sente próximo de tal forma que possa ligar-lhes a pedir ajuda?",
        "Com quantos amigos se sente à vontade para falar sobre assuntos pessoais?"
    ]

    for text in text_list:
        qorder += 1
        q = Question(
            name=text,
            order=qorder,
            question_type=qtype,
            section=section,
            quotation_max=5,
        )
        q.save()
        q.possible_answers.add(a1)
        q.possible_answers.add(a2)
        q.possible_answers.add(a3)
        q.possible_answers.add(a4)
        q.possible_answers.add(a5)
        q.possible_answers.add(a6)
        q.save()


def verificar_form_risk(value):
    if value is None or len(value) == 0:
        if type(value) is str:
            return ""
        else:
            return 0
    if type(value) is str:
        value = value.replace(".", ",")
    return value


def has_cuidador_flag(flag):
    return flag == 'cuidador'


def get_participant_or_cuidador(flag_boolean, id):
    if flag_boolean:
        return Cuidador.objects.get(pk=id)

    return Participante.objects.get(pk=id)


@login_required(login_url='login')
def dashboard_view(request):
    doctor = request.user
    participants = Participante.objects.filter(avaliador=doctor)
    resolutions = Resolution.objects.filter(doctor=doctor)

    context = {'participants': participants, 'resolutions': resolutions}
    return render(request, 'protocolo/dashboard.html', context)


@login_required(login_url='login')
def dashboard_content_view(request):
    doctor = request.user
    participants = Participante.objects.filter(avaliador=doctor)
    resolutions = Resolution.objects.filter(doctor=doctor)

    context = {'participants': participants, 'resolutions': resolutions}
    return render(request, 'protocolo/dashboardcontent.html', context)


@login_required(login_url='login')
def teste(resquest):
    return render(resquest, 'protocolo/teste.html')


@login_required(login_url='login')
def protocolos_view(request):
    context = {'protocolos': Protocol.objects.all().order_by('order')}
    return render(request, 'protocolo/protocolos.html', context)


@login_required(login_url='login')
def menu_protocolo_view(request):
    return render(request, 'mentha/app-list.html')


@login_required(login_url='login')
def popup_view(request):
    return render(request, 'protocolo/popupparts.html')


@login_required(login_url='login')
def registo_view(request):
    doctor = request.user

    if request.method == 'POST':
        try:
            user = Avaliador.objects.get(user=doctor)
        except Avaliador.DoesNotExist:
            try:
                user = Administrador.objects.get(user=doctor)
            except Administrador.DoesNotExist:
                user = None

        referenciacao = user.reference
        new_user = User()
        new_user.username = request.POST.get('username').replace(" ", "")
        new_user.password = request.POST.get('password')
        new_user.email = request.POST.get('email')
        new_user.save()

        my_group = DjangoGroup.objects.get(name='Participante')
        my_group.user_set.add(new_user)

        new_registo = InformacaoSensivel()
        new_registo.nome = request.POST.get('nome')
        new_registo.email = request.POST.get('email')
        new_registo.telemovel = request.POST.get('telemovel')
        new_registo.save()

        new_participante = Participante()
        new_participante.user = new_user
        new_participante.sexo = request.POST.get('sexo')
        new_participante.info_sensivel = new_registo
        new_participante.referenciacao = referenciacao
        new_participante.avaliador = doctor
        nascimento_str = request.POST.get('nascimento')
        nascimento_datetime = datetime.strptime(nascimento_str, '%Y-%m-%d')
        new_participante.nascimento = nascimento_datetime
        new_participante.save()

        return redirect('protocolo:participants')

    context = {}
    return render(request, 'protocolo/participantes_registo.html')


@login_required(login_url='login')
def avaliadores_registo_view(request):
    if request.method == 'POST':
        admin = Administrador.objects.get(user=request.user)

        new_user = User()

        new_user.username = request.POST.get('username')
        new_user.password = request.POST.get('password')
        new_user.email = request.POST.get('email')

        new_user.first_name = request.POST.get('primeiro_nome')
        new_user.last_name = request.POST.get('ultimo_nome')
        new_user.save()

        new_avaliador = Avaliador()
        new_avaliador.user = new_user
        new_avaliador.reference = admin.reference
        new_avaliador.save()

        my_group = DjangoGroup.objects.get(name='Avaliador')
        my_group.user_set.add(new_user)

        return redirect('protocolo:participants')

    context = {}
    return render(request, 'protocolo/avaliadores_registo.html')


@login_required(login_url='login')
def incrementar(request, part_id, participant_id):
    part = Part.objects.get(pk=part_id)
    particitant = Participante.objects.get(pk=participant_id)
    nome = part.nome + datetime.now
    partParticipant = ParteDoUtilizador(
        part=part, participante=particitant, nome=nome)

    return render(request, 'protocolo/parts.html')


@login_required(login_url='login')
def participant_risk_view(request, protocol_id):
    doctor = request.user
    protocolo = Protocol.objects.get(pk=protocol_id)
    participants = Participante.objects.filter(avaliador=doctor)
    resolutions = Resolution.objects.filter(doctor=doctor)

    context = {'participants': participants,
               'resolutions': resolutions, 'protocolo': protocolo}
    return render(request, 'protocolo/protocolo_participants_risk.html', context)
# funcao view para adicionar uma parte a um participante


@login_required(login_url='login')
def nova_pagina_risk_report(request):
    form_report_risk = Risk.objects.all()
    return render(request, 'protocolo/visualizacao_risk.html', {'form_report_risk': form_report_risk})


@login_required(login_url='login')
def parte_do_utilizador_add_view(request):
    if request.method == 'POST':
        partId = request.POST.get('partId')
        part = Part.objects.get(pk=partId)
        patient = Participante.objects.get(pk=request.POST.get('patientId'))
        parteDoUtilizador = ParteDoUtilizador(part=part, participante=patient)
        parteDoUtilizador.save()

    context = {
        'parteDoUtilizador': parteDoUtilizador,
        'part': part,

    }
    return HttpResponse('200')
    # return JsonResponse({}, status=201)


@login_required(login_url='login')
def parte_view(request):
    parte = Part.objects.all()  # participante = patient)
    # patient = Participante.objects.get(pk=patient_id)
    botao_clicado = int(request.GET.get('botao_clicado ', 0))
    context = {
        'parte': parte,
        'botao_clicado': botao_clicado,
        # 'patient':patient
    }
    return render(request, 'protocolo/parts.html', context)


@login_required(login_url='login')
def parts_view(request, protocol_id, patient_id, is_cuidador='is_participante'):
    start = time.time()
    protocol = Protocol.objects.get(pk=protocol_id)
    if is_cuidador == 'is_cuidador':
        cuidador = Cuidador.objects.get(pk=patient_id)
        # Mudar request.user para o patient depois
        resolutions = Resolution.objects.filter(
            doctor=request.user, cuidador=cuidador)
        parts = ParteDoUtilizador.objects.filter(cuidador=cuidador)
        patient = cuidador  # talvez precise disto para o url renderizar
    else:
        patient = Participante.objects.get(pk=patient_id)
        # Mudar request.user para o patient depois
        resolutions = Resolution.objects.filter(
            doctor=request.user, patient=patient)
        parts = ParteDoUtilizador.objects.filter(participante=patient)

    parte = Part.objects.all()

protocolo/templates/protocolo/checkbox_question.html
<form class="flex-container" id="question-form" action="" method="post">
    <input type="hidden" name="type" value="0">
    {% csrf_token %}
    <div class="flex-choices flex-item padding-top-25">
        {% for answer in question.possible_answers.all %}
        <label>
            <input class="" id="{{ answer.id }}" name="choice" type="checkbox" value="{{ answer.id }}" 
            {% if answer.id in existing_answer_id %} 
            
                checked="checked" 
            
            {% endif %} />
            {{ answer.name }}
        </label>
        <br>

        {% endfor %}
    </div>

    <div class="flex-textarea flex-item padding-top-25">
        <label><b>Apontamentos</b></label>
        <textarea style="white-space: pre-line" class="notes-area form-control" id="notes"
            name="notes">{{ notes }}</textarea>
    </div>
    <br>

    <div class="flex-buttons">
        <button class="btn jq-btn flex-left mb-btn-outline" {% if question.section.dimension.number_of_questions > 1 %}
            data-href="{% url 'protocolo:sections' protocol.id part.id area.id instrument.id dimension.id patient.id %}{% if is_cuidador == 'is_cuidador' %}/is_cuidador{% endif %}"
            {% else %}
            data-href="{% url 'protocolo:dimensions' protocol.id part.id area.id instrument.id patient.id %}{% if is_cuidador == 'is_cuidador' %}/is_cuidador{% endif %}"
            {% endif %}
            type="button">

            <i class="fa-solid fa-chevron-left"></i>&nbsp; Anterior
        </button>
        <button class="btn btn-submit mb-btn-outline flex-right"
            data-href="{% url 'protocolo:question' protocol.id part.id area.id instrument.id dimension.id section.id patient.id %}{% if is_cuidador == 'is_cuidador' %}/is_cuidador{% endif %}"
            style="" type="submit">
            <i class="fa fa-check"></i>&nbsp; Submeter
        </button>
    </div>

</form>

protocolo/templates/protocolo/mcq_question.html
{% load markdownify %}
{% block script %}
    <script>
        function submitForm() {
            var radios = document.querySelectorAll('input[name="choice"]');
            var isChecked = false;

            for (var i = 0; i < radios.length; i++) {
                if (radios[i].checked) {
                    isChecked = true;
                    break;
                }
            }

            if (!isChecked) {
                alert('Please select an option');
                return false; // Prevent form submission
            }
        }
    </script>
{% endblock %}
<form class="flex-container" id="question-form" action="" method="post">
    <input type="hidden" name="type" value="0">
    {% csrf_token %}
    <div class="flex-choices flex-item padding-top-25" style="width:100%">
        {% for answer in question.possible_answers.all %}
            <label for="{{answer.id}}">
                <input class="" id="{{ answer.id }}" name="choice" type="radio" value="{{ answer.id }}"
                        {% if answer.id in existing_answer_id %}
                       checked="checked"
                        {% endif %}
                />
                {{ answer.name }}
            </label>
            <br>
        {% endfor %}
    </div>

    <div class="flex-textarea flex-item padding-top-25" style="width:100%">
        <label for="notes"><b>Apontamentos</b></label>
        <textarea style="white-space: pre-line" class="notes-area form-control" id="notes"
                  name="notes">{{ notes }}</textarea>
    </div>
    <br>

    <div class="flex-buttons">
        <button class="btn jq-btn btn-primary flex-left mb-btn-outline"
                {% if question.section.dimension.number_of_questions > 1 %}
                data-href="{% url 'protocolo:sections' protocol.id part.id area.id instrument.id dimension.id patient.id %}{% if is_cuidador == 'is_cuidador' %}/is_cuidador{% endif %}"
                {% elif question.name == 'Cooperação dada na entrevista' or question.name == 'Relação com o Avaliador' %}
                data-href="{% url 'protocolo:areas' protocol.id part.id patient.id %}{% if is_cuidador == 'is_cuidador' %}/is_cuidador{% endif %}"
                {% else %}
                data-href="{% url 'protocolo:dimensions' protocol.id part.id area.id instrument.id patient.id %}{% if is_cuidador == 'is_cuidador' %}/is_cuidador{% endif %}"
                {% endif %}
            type="button">
            <i class="fa fa-chevron-left"></i>&nbsp; Anterior
        </button>
        <button class="btn mb-btn-outline btn-submit flex-right"
                data-href="{% url 'protocolo:question' protocol.id part.id area.id instrument.id dimension.id section.id patient.id %}{% if is_cuidador == 'is_cuidador' %}/is_cuidador{% endif %}"
                type="submit">
            <i class="fa fa-check"></i>&nbsp; Submeter
        </button>
    </div>

</form>

protocolo/templates/protocolo/protocolo_participants_risk.html
{% load tags %}
<div id="wrapper">
    <div class="d-flex flex-column" id="content-wrapper">
        <div id="content">
            <div class="container-fluid">
                <div class="card shadow">
                    <div class="card-header py-3">
                        <p class="text-primary m-0 fw-bold" style="font-size: 20px;">{{ protocolo.name }}</p>
                    </div>
                    <div class="card-body">
                        <p><b>Introdução:</b><br>
                            Está prestes a realizar uma Avaliação. <br>
                            Para realizar uma avaliação, prima o botão "Aplicar Teste" referente ao paciente que deseja
                            avaliar.</p>
                        <div class="table-responsive">
                            <table class="table table-hover-light">
                                <thead>
                                    <tr>
                                        <th style="text-align: left;width: 15%">Nome</th>
                                        <th style="text-align: center;">Idade</th>
                                        <th style="text-align: center;">Sexo</th>
                                        <th style="text-align: center;">Teste1</th>
                                        <th style="text-align: center;">Teste2</th>
                                        <th style="text-align: center;">teste3</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for p in participants %}
                                    <tr>
                                        <td><a href="#" class="jq-btn no-decor"
                                                data-href="{% url 'protocolo:participant' p.id %}">
                                                {{ p.nome }}
                                                <svg style="margin-top: 0px;" xmlns="http://www.w3.org/2000/svg"
                                                    width="16" height="16" fill="currentColor" class="bi bi-link"
                                                    viewBox="0 0 16 16">
                                                    <path
                                                        d="M6.354 5.5H4a3 3 0 0 0 0 6h3a3 3 0 0 0 2.83-4H9c-.086 0-.17.01-.25.031A2 2 0 0 1 7 10.5H4a2 2 0 1 1 0-4h1.535c.218-.376.495-.714.82-1z" />
                                                    <path
                                                        d="M9 5.5a3 3 0 0 0-2.83 4h1.098A2 2 0 0 1 9 6.5h3a2 2 0 1 1 0 4h-1.535a4.02 4.02 0 0 1-.82 1H12a3 3 0 1 0 0-6H9z" />
                                                </svg>
                                            </a>
                                            <a href="#" class="jq-btn no-decor"
                                                data-href="{% url 'protocolo:participant-overview' p.id %}">
                                                <br>
                                                <i class="fas fa-eye"></i> Visão Geral
                                            </a>
                                        </td>
                                        <td style="text-align: center;">{% calculate_age p.nascimento %}</td>
                                        <td style="text-align: center;">{{ p.sexo|make_list|first }}</td>
                                        <td style="text-align: center;">Teste 1</td>
                                        <td style="text-align: center;">Teste 2</td>
                                        <td style="text-align: center;">Teste 3</td>
                                        <td style="text-align: center;"><a id="{{ protocoloo.id }}" href="#"
                                                class="jq-btn"
                                                data-href="{% url 'protocolo:parts' protocolo.id p.id %}">
                                                <button class="btn btn-primary" type="button"
                                                    style="border-radius: 217px;">
                                                    <i class="fa fa-chevron-right"
                                                        style="border-left-width: 0px;font-size: 15px;text-align: right;"></i>
                                                </button>
                                            </a></td>
                                    </tr>
                                    {% empty %}
                                    Não tem Participantes associados.
                                    {% endfor %}
                                    <tr></tr>
                                </tbody>
                                <!-- Bold footer line -->
                                <tfoot>
                                    <tr>
                                        <td><strong></strong></td>
                                        <td><strong></strong></td>
                                        <td><strong></strong></td>
                                        <td><strong></strong></td>
                                        <td><strong></strong></td>
                                        <td><strong></strong></td>
                                        <td><strong></strong></td>
                                        <td><strong></strong></td>
                                        <td><strong></strong></td>
                                        <td><strong></strong></td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                        <!-- Buttons -->
                        <div class="flex-buttons">
                            <button id="previous" class="btn jq-btn btn-primary flex-left mb-btn"
                                data-href="{% url 'protocolo:protocols' %}" type="button">
                                <i class="fa fa-chevron-left"></i>&nbsp; Anterior
                            </button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>

protocolo/templates/protocolo/timer_tmt_question.html
<form class="flex-container" id="question-form" action="" method="post" >
    <input type="hidden" name="type" value="0">
    {% csrf_token %}
    <br>
    <div style="align-items: flex-start" class="form-row row-md-12 padding-top-25 flex-header">
        <div style="width: 50%" class="left">
        <div class="col col-md-6 ">
            <label><b>Erros de Sequenciação</b></label><br>
            <input class="form-control" name="sequenciacao" type="number" value="{{ Sequenciacao }}">
        </div>
        <div class="col col-md-6 ">
            <label><b>Erros perseverativos</b></label><br>
            <input class="form-control" name="perseverativos" type="number" value="{{ Perseverativos }}">
        </div>
        <div class="col col-md-6 ">
            <label><b>Erros de proximidade</b></label><br>
            <input class="form-control" name="proximidade" type="number" value="{{ Proximidade }}">
        </div>
            <div class="col col-md-6 ">
            <label><b>Tempo (em segundos)</b></label><br>
            <input class="form-control" name="tempo" type="number" value="{{ Tempo }}">
        </div>
            </div>
        <div style="width: 50%"class="right">
            <h1 style="padding-top:15px;text-align: right;">
        <button class="btn btn-primary btn-timer" type="button" style="border-radius: 217px;background-color: var(--bs-btn-bg);">
            <i id="timer-ico" class="fa fa-play" style="border-left-width: 0px;font-size: 15px;text-align: right;"></i>
        </button>
        <span id="clock" class="clock">0:00</span></h1>
        </div>
    </div>
    <div class="flex-textarea flex-item padding-top-25">
        <label><b>Apontamentos</b></label>
        <textarea style="white-space: pre-line" class="notes-area form-control" id="notes"
                  name="notes">{{ notes }}</textarea>
    </div>
    <br>

    <div class="flex-buttons">
        <button class="btn jq-btn btn-primary flex-left mb-btn"
                {% if question.section.dimension.number_of_questions > 1 %}
                data-href="{% url 'protocolo:sections' protocol.id part.id area.id instrument.id dimension.id patient.id %}"
                {% else %}
                data-href="{% url 'protocolo:dimensions' protocol.id part.id area.id instrument.id patient.id %}"
                {% endif %}
            type="button">
            <i class="fa fa-chevron-left"></i>&nbsp; Anterior
        </button>
        <button class="btn btn-submit btn-primary mb-btn flex-right"
                data-href="{% url 'protocolo:question' protocol.id part.id area.id instrument.id dimension.id section.id patient.id %}"
                style="" type="submit">
            <i class="fa fa-check"></i>&nbsp; Submeter
        </button>
    </div>

</form>

protocolo/templates/protocolo/visualizacao_risk.html
{% load static %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.2/jspdf.min.js"></script>
<script src="{% static 'protocolo/js/visualizacao_risk.js' %}"></script>

{% for risco in form_report_risk %}
<p>teste</p>
    <p>Idade: {{ form_report_risk.idade }}</p>
    <p>Sexo: {{ form_report_risk.sexo }}</p>
    <p>Fumador: {{ form_report_risk.fumador }}</p>
    <p>Pressao_arterial: {{ form_report_risk.pressao_arterial }}</p>
    <p>Risco: {{ form_report_risk.risco_de_enfarte }}</p>
    <p>Comentário: {{ form_report_risk.comentario }}</p>

{% endfor %}
</div>
