config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('diario/', include('diario.urls')),
    path('protocolo/', include('protocolo.urls')),
    path("to-c", include("clients.urls")),
    path('', include('mentha.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diario/urls.py
from diario import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'diario'
urlpatterns = [
                  path('nextSession', views.nextSession, name="nextSession"),
                  # path('app-list',views.menu_view,name='app-list'),
                  path('logout_care_view', views.logout_care_view, name="logout_care_view"),
                  path('login', views.login_care_view, name="login", ),
                  path('register', views.register_user, name="register"),
                  path('p_view/<str:cuidador_id>/<str:grupo_id>', views.profile_care_view, name='p_view'),
                  path('', views.dashboard, name="dashboard_Care"),
                  path('create_caregiver', views.create_caregiver, name="create_caregiver"),
                  path('create_participante/<str:grupo_id>', views.create_participante, name="create_participante"),
                  path('create_mentor/<str:grupo_id>', views.create_mentor, name="create_mentor"),
                  path('create_colaborador', views.create_colaborador, name="create_colaborador"),
                  path('grupo_details/<int:grupo_id>', views.view_group_details, name="grupo_details"),
                  path('delete_groups/<str:grupo_id>', views.delete_groups, name='delete_grupos'),
                  path('update_groups/<str:grupo_id>', views.update_groups, name="update_groups"),
                  path('filter_group/<int:cuidador_id>', views.filter_group, name='filter_group'),
                  path('new_group', views.new_group, name="new_group"),
                  path('assign_group/<int:grupo_id>/<int:cuidador_id>', views.assign_group, name='assign_group'),
                  path('guarda_grupo', views.guarda_grupo, name="guarda_grupo"),
                  path('group_members/<int:grupo_id>', views.group_members, name='group_members'),
                  path('group_sessions/<int:grupo_id>', views.group_sessions, name='group_sessions'),
                  path('group_notes/<int:grupo_id>', views.group_notes, name='group_notes'),
                  path('create_dinamizador/<str:grupo_id>', views.create_dinamizador, name="create_dinamizador"),
                  path('colaborador_update/<str:colaborador_id>', views.colaborador_update,
                       name='colaborador_update'),
                  path('dinamizador_update/<str:dinamizador_id>/<str:grupo_id>', views.dinamizador_update,
                       name='dinamizador_update'),
                  path('mentor_update/<str:mentor_id>/<str:grupo_id>', views.mentor_update,
                       name='mentor_update'),
                  path('dinamizador_delete/<str:dinamizador_id>/<str:grupo_id>', views.dinamizador_delete,
                       name='dinamizador_delete'),
                  path('caregiver_update/<str:cuidador_id>/<str:grupo_id>', views.caregiver_update,
                       name='caregiver_update'),
                  path('participante_update/<str:participante_id>/<str:grupo_id>', views.participante_update,
                       name='participante_update'),
                  path('caregiver_delete/<str:cuidador_id>/<str:grupo_id>', views.caregiver_delete,
                       name='caregiver_delete'),
                  path('assign_dinamizador/<int:grupo_id>/<int:dinamizador_id>', views.assign_dinamizador,
                       name='assign_dinamizador'),
                  path('assign_mentor/<int:grupo_id>/<int:mentor_id>', views.assign_mentor,
                       name='assign_mentor'),
                  path('assign_participante/<int:grupo_id>/<int:participante_id>', views.assign_participante,
                       name='assign_participante'),
                  path('assign_caregiver/<int:grupo_id>/<int:cuidador_id>', views.assign_caregiver,
                       name='assign_caregiver'),
                  path('diario/<int:idGrupo>/<int:idSessao>', views.view_diario, name='diario'),
                  path('diario_participante/<int:idSessaoGrupo>/<int:idParticipante>', views.view_diario_participante,
                       name='diario_participante'),
                  path('diario_grupo/<int:idSessaoGrupo>', views.view_diario_grupo, name='diario_grupo'),
                  path('atualizaPresencasDiario/<int:idSessaoGrupo>', views.view_atualiza_presencas_diario,
                       name='atualiza_presencas_diario'),
                  path('questionario_satisfacao/<int:idPergunta>/<int:idParte>/<int:sessaoGrupo>',
                       views.view_questionario_satisfacao,
                       name="questionario_satisfacao"),
                  path('questionario/<int:idPergunta>/<int:idParte>/<int:sessaoGrupo>', views.view_questionario,
                       name="view_questionario"),
                  path('exercicio/<int:idExercicio>/<int:parteGrupo>/<int:sessaoGrupo>', views.view_exercicio,
                       name="exercicio"),
                  path('abrirQuestionario/<int:idPergunta>/<int:idParte>/<int:sessaoGrupo>',
                       views.view_abrirQuestionario,
                       name="view_abrirQuestionario"),
                  path('resultados/<int:idPergunta>/<int:idParte>/<int:sessaoGrupo>', views.view_resultados,
                       name='resultados'),
                  path('parte/<int:parte_do_grupo_id>/<int:sessaoGrupo_id>/<str:estado>/<int:proxima_parte>',
                       views.view_parte, name="parte"),
                  path('parteDetalhes/<int:parte_do_grupo_id>/<int:sessaoGrupo_id>/<int:idGrupo>',
                       views.view_parteDetalhes,
                       name="parteDetalhes"),
                  path('finalizar_parte/<int:idParte>/<int:sessao_grupo_id>/<str:estado>', views.finalizar_parte,
                       name='finalizar_parte'),
                  path('finalizar_sessao/<int:idGrupo>/<int:sessao_grupo_id>', views.finalizar_sessao,
                       name='finalizar_sessao'),
                  path('iniciar_sessao/<int:sessao_grupo_id>', views.view_iniciar_sessao, name='iniciar_sessao'),
                  path('changeDate/<int:sessao_id>/<int:group_id>', views.view_changeDate, name='changeDate'),
                  path('sessao/<int:sessao_grupo_id>/<int:grupo_id>', views.view_sessao, name='sessao'),
                  path('presencas_sessao/<int:proxima_id>', views.view_presencas_sessao, name='presencas_sessao'),
                  path('voltar_parte/<int:idParte>/<int:sessao_grupo_id>/<str:estado>', views.voltar_parte,
                       name='voltar_parte'),
                  path('partilha_parte/<int:sessaoGrupo>/<int:idParteExercico>', views.partilha_parte,
                       name='partilha_parte'),
                  path(
                      'guarda_resposta/<int:sessaoGrupo_id>/<int:parteGrupo_id>/<int:utilizador_id>/<int:pergunta_id>/<int:parte_exercicio_id>',
                      views.guarda_resposta_view, name="guarda_resposta"),
                  path('avaliacao_participantes/<int:sessaoGrupoid>', views.view_avaliacao_participantes,
                       name="avaliacao_participantes"),
                  #    path('respostas/<int:idSessaoGrupo>/<int:idParticipante>/', views.respostas_view,
                  #         name="respostas"),
                  path('guarda_avaliacao_participante/<int:sessaoGrupo_id>', views.guarda_avaliacao_participante,
                       name="guarda_avaliacao_participante"),
                  path('guarda_avaliacao_sessao/<int:sessaoGrupo_id>', views.guarda_avaliacao_sessao,
                       name="guarda_avaliacao_participante"),
                  path('obter_candidatos', views.obter_cadidatos, name="obter_candidatos"),
                  path('parte_ativa/<int:sg_id>', views.parte_ativa, name="parte_ativa"),
                  path('user_dashboard', views.user_dashboard, name="user_dashboard"),
                  path('streamss/', views.streams, name="streams"),
                  path('get_token/', views.getToken, name="get_token"),
                  path('complete_partilha/<int:partilha_id>/', views.complete_partilha, name='complete_partilha'),
                  path('remove_partilha/<int:partilha_id>/', views.remove_partilha, name='remove_partilha'),
                  path('colaboradores', views.colaboradores, name='colaboradores'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mentha/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'mentha'

urlpatterns = [
                  path('', views.index_page_view, name='index'),
                  path('home/', views.home_page_view, name='home'),
                  path('noticias/', views.noticias_page_view, name='noticias'),
                  path('projeto/', views.projeto_page_view, name='projeto'),

                  path('aplicacoes/', views.aplicacoes_page_view, name='aplicacoes'),
                  path('mentha-cog/', views.mentha_cog_page_view, name='mentha-cog'),
                  path('mentha-care/', views.mentha_care_page_view, name='mentha-care'),
                  path('protocolo-mentha/', views.protocolo_mentha_page_view, name='protocolo-mentha'),

                  path('app-list/', views.app_list_view, name='app-list'),

                  path('parceiros/', views.parceiros_page_view, name='parceiros'),
                  path('equipa/', views.equipa_page_view, name='equipa'),

                  path('contacto/', views.contacto_page_view, name='contacto'),
                  path('videoconferencia/', views.videoconferencia_page_view, name='videoconferencia'),
                  path('zoom-div/', views.zoom_div_page_view, name='zoom-div'),
                  path('login/', views.login_page_view, name='login'),
                  path('logout/', views.logout_page_view, name='logout'),
                  path('forgot_password/', views.forgot_password, name='forgot_password'),
                  path('resetar/<uidb64>/<token>/', views.password_reset_confirm, name='password_resetar_confirm'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

protocolo/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "protocolo"

urlpatterns = [
                path('', views.protocolos_view, name="protocols"),
                path('incrementar/<int:part_id>/<int:participant_id>', views.incrementar, name='incrementar'), #estou só a fazer testes!
                path('dashboard', views.dashboard_view, name="dashboard"),
                path('popup',views.popup_view,name = 'popup'),
                path('', views.menu_protocolo_view, name="app-view"),
                #path('risk',views.risk_form_view,name="risk"),
                path('teste', views.teste, name='teste'),
                path('participant/<int:protocol_id>', views.participant_risk_view, name='participant_risk'),
                path('protocol-participants/<int:protocol_id>', views.protocol_participants_view,
                    name="protocol-participants"),
                path('participants', views.participants_view, name="participants"),
                path('dashboard-content', views.dashboard_content_view, name="dashboard-content"),
                path('atualizar-tabela', views.parte_do_utilizador_add_view, name = "atualizar-tabela"),

                path('parts/<int:protocol_id>/<int:patient_id>', views.parts_view, name="parts"),
                path('parts/<int:protocol_id>/<int:patient_id>/<str:cuidador>', views.parts_view, name="parts"),

                path('parte', views.parte_view, name = "parte"),

                path('areas/<int:protocol_id>/<int:part_id>/<int:patient_id>', views.areas_view, name="areas"),
                path('areas/<int:protocol_id>/<int:part_id>/<int:patient_id>/<str:is_cuidador>', views.areas_view, name="areas"),

                path('instruments/<int:protocol_id>/<int:part_id>/<int:area_id>/<int:patient_id>', views.instruments_view, name="instruments"),
                path('instruments/<int:protocol_id>/<int:part_id>/<int:area_id>/<int:patient_id>/<str:is_cuidador>', views.instruments_view, name="instruments"),

                #path('risco', views.risco_view, name="risco"),
                path('dimension/<int:protocol_id>/<int:part_id>/<int:area_id>/<int:instrument_id>/<int:patient_id>',
                    views.dimensions_view, name="dimensions"),
                path('dimension/<int:protocol_id>/<int:part_id>/<int:area_id>/<int:instrument_id>/<int:patient_id>/<str:is_cuidador>',
                    views.dimensions_view, name="dimensions"),

                path('section/<int:protocol_id>/<int:part_id>/<int:area_id>/<int:instrument_id>/<int:dimension_id>/<int:patient_id>',
                    views.sections_view, name="sections"),
                path('section/<int:protocol_id>/<int:part_id>/<int:area_id>/<int:instrument_id>/<int:dimension_id>/<int:patient_id>/<str:is_cuidador>',
                    views.sections_view, name="sections"),

                path('question/<int:protocol_id>/<int:part_id>/<int:area_id>/<int:instrument_id>/<int:dimension_id>/<int:section_id>/<int:patient_id>',
                    views.question_view, name="question"),
                path('question/<int:protocol_id>/<int:part_id>/<int:area_id>/<int:instrument_id>/<int:dimension_id>/<int:section_id>/<int:patient_id>/<str:is_cuidador>',
                    views.question_view, name="question"),

                path('report2/<int:resolution_id>', views.report2, name="report2"),
                path('nova_pagina_risk_report/',views.nova_pagina_risk_report, name='nova_pagina_risk_report'),
                path('report/<int:resolution_id>', views.report_view, name="report"),
                path('report_risk',views.report_risk,name="report_risk"), #estou só a fazer testes! A ver se este funciona
                path('login', views.login_view, name="login"),
                path('logout', views.logout_view, name="logout"),
                path('profile/<int:participant_id>/', views.profile_view, name="participant"),
                path('delete_button/<int:partedoutilizador_id>/<int:participant_id>', views.delete_button, name='delete_button'),
                path('participantes_registo/',views.registo_view,name="participantes_registo"),
                path('avaliadores_registo/',views.avaliadores_registo_view,name="avaliadores_registo"),
                path('participant-overview/<int:participant_id>/', views.patient_overview_view,
                    name="participant-overview"),
                path('participante_update/<str:participante_id>', views.participante_update,
                    name='participante_update'),
                path('cuidador_update/<str:cuidador_id>', views.cuidador_update,
                         name='cuidador_update'),
                path(
                    'gds-overview/<int:protocol_id>/<int:part_id>/<int:area_id>/<int:instrument_id>/<int:patient_id>',
                    views.gds_overview_view,
                    name="gds-overview"),
                path('colaboradores', views.colaboradores_view, name="colaboradores"),
                path('profile_cuidador/<int:cuidador_id>/', views.profile_cuidador_view, name="profile_cuidador"),
                path('exportar_risk/', views.export_risk_to_csv, name='export_risk_to_csv'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mentha/forms.py
from django import forms
from django.forms import ModelForm

from .models import Contacto

# Create your models here.
class ContactoForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nome'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['telefone'].widget.attrs.update({'class': 'form-control'})
        self.fields['assunto'].widget.attrs.update({'class': 'form-control'})
        self.fields['distrito'].widget.attrs.update({'class': 'form-control'})
        self.fields['referenciacao'].widget.attrs.update({'class': 'form-control'})
        self.fields['mensagem'].widget.attrs.update({'class': 'form-control', 'rows':5, 'placeholder':'Insira a sua mensagem...'})
    
    
    class Meta:
        model = Contacto
        fields = '__all__'

        labels = { 'referenciacao': 'Instituição Referenciadora'}


mentha/templates/mentha/app-list.html
{% load static %}

<div class="app-list" 
style="
display: flex;
justify-content: space-evenly;
align-items: center;
align-content: center;
margin-top:15px;
gap:15px;
">
    {% if 'COG' in show %}
        <a href="{% url 'diario:dashboard_Care' %}?flag=cog">
            <button class="btn mb-btn">
                <img src="{% static 'diario/img/cog.svg' %}" style="width:20px;display:inline-block"></i>
                MentHA-COG
            </button> 
        </a>
    {% endif %}
    {% if 'CARE' in show %}
        <a href="{% url 'diario:dashboard_Care' %}?flag=care">
            <button class="btn mb-btn">
                <i class="fa-solid fa-user-doctor"></i>
                MentHA-CARE
            </button>
        </a>
    {% endif %}
    {% if 'Protocolo' in show %}
        <a href="{% url 'protocolo:dashboard' %}">
            <button class="btn mb-btn">
                <i class="fa-solid fa-user-check"></i>
                MentHA-EVAL
            </button> 
        </a>
    {% endif %}
</div>

mentha/templates/mentha/noticias.html
<div id="noticias">

    <div class="blue">
        <div class="titulo">Notícias</div>
        <div class="texto">
            
        </div>
    </div>

    <div class="hero" style="height: 10em;">
        <div class="next">
            <span class="material-symbols-outlined">expand_more</span>
        </div>
    </div>

    {% for noticia in noticias %}

    <div class="blue">
        <div class="subtitulo">
            <div class="left">{{ noticia.titulo }}</div>
            <div class="right">({{ noticia.data }})</div>
        </div>
        <div class="noticia">
            {% load markdownify %}
            <div class="texto">{{ noticia.texto|markdownify }}</div>
            
            {% if noticia.url  %}
                <div class="referencia">         
                    Para saber mais: <span class="url"><b><a href="{{ noticia.url }}">Link</a></b></span>                  
                </div>
            {% endif %}
        
            {% if noticia.imagem %}
                <div class="imagem"> <img src="{{ noticia.imagem.url }}" alt=""> </div>
            {% endif %}
            
        </div>
    </div>

    
    <div class="hero" style="height: 10em;">
        <div class="next">
            <span class="material-symbols-outlined">expand_more</span>
        </div>
    </div>
    {% endfor %}

</div>

mentha/templates/mentha/password_reset_confirm.html
<!DOCTYPE html>
<html>
<head>
    <title>Reset Password</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #4eb4be;
            margin: 0;
            padding: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            background-color: #ffffff;
            padding: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            text-align: center;
        }

        h1 {
            font-size: 24px;
            margin-bottom: 20px;
        }

        form {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            margin-top: 20px;
        }

        input[type="password"] {
            width: 300px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
            margin-bottom: 10px;
        }

        input[type="text"] {
            width: 300px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
            margin-bottom: 10px;
        }

        input[type="checkbox"] {
            margin-left: 2px;
        }

        label {
            font-size: 13px;
        }

        input[type="submit"] {
            width: 150px;
            padding: 10px;
            background-color: #264b5d;
            margin-top: 5px;
            color: #fff;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #0056b3;
        }

        .error {
            color: #ff0000;
            margin-top: 10px;
        }

        .success {
            display: flex;
            color: #008000;
            margin-top: 10px;
        }
    </style>
</head>
<body>
<div class="container">
    <h1>Reset Password</h1>
    {% if success %}
        <div class="success" style="display: flex; flex-direction: column">
            <p>{{ success }}</p>
            <a href="{% url 'mentha:index' %}">Voltar para Home</a>
        </div>
    {% else %}
        {% if form.errors %}
            <p>Erros:</p>
        {% endif %}

        {% for key, val in form.errors.items %}
            <p class="error">{{ val }}</p>
        {% endfor %}

        <p>Olá, o seu username é {{ username }}</p>

        <p>Tente novamente:</p>

        <form action="{% url 'mentha:password_resetar_confirm' uidb64 token %}" method="post">
            {% csrf_token %}
            <input id="id_password" type="password" name="new_password1" placeholder="Nova senha" required
                   autocomplete="none">
            <input id="id_password_confirm" type="password" name="new_password2" placeholder="Confirme a senha"
                   required>
            <div style="display: flex; align-items: center; gap: 2px">
                <input type="checkbox" id="showPasswordToggle" style="margin-left: 2px">
                <label for="showPasswordToggle" class="form-check-label" style="font-size: 13px">Mostrar
                    password</label>
            </div>
            <input type="submit" value="Reset Password">
        </form>
    {% endif %}
    </div>

    <script>
        const showPasswordToggle = document.getElementById('showPasswordToggle');
        const passwordInput1 = document.getElementById('id_password');
        const passwordInput2 = document.getElementById('id_password_confirm');

        showPasswordToggle.addEventListener('change', function () {
            passwordInput1.type = this.checked ? 'text' : 'password';
            passwordInput2.type = this.checked ? 'text' : 'password';
        });
    </script>
</body>
</html>

mentha/templates/mentha/protocolo-mentha.html
<div id="programa">
    {% load static %}
    <div class="espacolista"></div>
    <div class="espacolista"></div>

    <div class="blue caixa">

        <div class="principal">

            <div class="titulo">
                Protocolo de Avaliação “MentHA-Assessment”
            </div>

            <div class="texto">

                <h3 class="subtitulo">Introdução</h3>

                <p>O protocolo de avaliação MentHA é um instrumento composto por várias provas neuropsicológicas
                    que tem por objectivo monitorizar o impacto do programa de Estimulação Cognitiva MentHA-COG
                    através de uma avaliação global da pessoa antes e depois da intervenção (pré-pós).
                </p>

                <p>A avaliação baseia-se em testes de aplicação breve (i) frequentemente utilizados na prática
                    clínica (internacional e nacional), (ii) com reconhecida qualidade técnica na identificação
                    das funções cognitivas e (iii) devidamente validados para a população portuguesa.
                </p>

                <p>As diferentes provas, complementares entre si, visam a avaliação dos seguintes domínios: (i)
                    neurocognitivo (atenção complexa, função executiva, aprendizagem e memória linguagem
                    perceptivomotor e a cognição social), (i) emocional (ansiedade, depressão), (iii) funcional
                    (actividades básicas e instrumentais de vida diária) e (iv) comportamental (sintomatologia
                    psicopatológica).
                </p>

                <p>O Protocolo está dividido em 2 partes, de acordo com a avaliação de variáveis de estudo e da
                    intervenção.
                </p>

                <p>A 1ª parte permite caracterizar os participantes, após a fase de referenciação e perceber se
                    a mesma reúne os critérios necessários para integrar o programa.
                </p>


                <h3 class="subtitulo">Critérios de Inclusão</h3>

                <ul>

                    <li>Idade igual ou superior a 50 anos</li>

                    <li>Diagnóstico Neuropsiquiátrico</li>

                    <li>Queixas cognitivas, Defeito cognitivo ligeiro ou Demência</li>

                    <li>Cuidador informal ou formal (identificado)</li>

                </ul>


                <h3 class="subtitulo">Avaliação de Estudo</h3>

                <p>Com rastreio subjacente ao nível da entrevista clínica* preferencialmente com a presença do
                    informante/cuidador:</p>

                <ul type="a">

                    <li>Caracterização sócio-demográfica;</li>

                    <li>Consciência Humor e Comportamento;</li>

                    <li>Cooperação dada no Exame;</li>

                    <li>Relação com o Avaliador;</li>

                    <li>Funcionalidade (Básica);</li>

                    <li>Avaliação Psicológica;</li>

                    <li>Personalidade;</li>

                </ul>

                <p>A 2ª parte consiste na avaliação de variáveis referentes à intervenção sendo aplicadas nas fases
                    “pré-teste“ e “pós-teste”. Avaliação de Intervenção ("Pré-Pós"):</p>

                    <ul type="a">

                        <li>Funcionalidade (Instrumental);</li>
                        <li>Cognição;</li>
                        <li>Humor;</li>
                        <li>Estádio de Deterioração (GDS 1-7)</li>
                    </ul>

                <h3 class="subtitulo">Local de avaliação</h3>
                            
                <p>Em termos práticos, o 1º momento de avaliação deverá ser realizado nas instituições de
                    referência protocoladas com os parceiros locais e o 2º momento no local da intervenção
                    (comunidade), a fim de se assegurar a diferença entre “Projecto-Estudo” e o “Programa”
                    (comunitário).</p>
                

                <h3 class="subtitulo">Materiais</h3>
                
                <p>Por razões de facilidade de manuseamento e de ritmo de aplicação da bateria, construiu-se um
                    caderno de respostas e o caderno com as principais instruções de aplicação de cada instrumento.</p>
                
            </div>
        </div>
    </div>


    <div class="espacolista"></div>


    <div class="espacolista"></div>

</div>

mentha/templates/mentha/videoconferencia.html
<div id="videoconferencia" class="hero">

    <div class="espacolista"></div>

    <div class="branco">
        <div class="titulo">Videoconferencia</div>
        <div class="texto">
            <p>Entre no Zoom e junte-se à sua sessão, ou use para falar com os colegas do seu grupo.</p>
            <button id="zoom-button" class="btn btn-primary  btn-lg btn-block" style="opacity:1; background-color:#4EB4BE;color:white;">Entrar no Zoom</button>
        </div>
    </div>

    <div class="espacolista"></div>

    <div id="zoom" class="blue" style="display:none;">
    </div>
</div>

mentha/templates/mentha/zoom-div.html
<iframe src="https://videoconf-colibri.zoom.us/j/85178600865?pwd=amcramcrZW9lZWJUQUVsVXcvelRyQT09"
    style="border: 0; width: 100%; height:50vh;" allow="microphone; camera; fullscreen"
    sandbox="allow-forms allow-scripts allow-same-origin">
</iframe>