config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('diario/', include('diario.urls')),
    path('protocolo/', include('protocolo.urls')),
    path("to-c", include("clients.urls")),
    path('', include('mentha.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diario/urls.py
from diario import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

app_name = 'diario'
urlpatterns = [
                  path('nextSession', views.nextSession, name="nextSession"),
                  # path('app-list',views.menu_view,name='app-list'),
                  path('logout_care_view', views.logout_care_view, name="logout_care_view"),
                  path('login', views.login_care_view, name="login", ),
                  path('register', views.register_user, name="register"),
                  path('p_view/<str:cuidador_id>/<str:grupo_id>', views.profile_care_view, name='p_view'),
                  path('', views.dashboard, name="dashboard_Care"),
                  path('create_caregiver', views.create_caregiver, name="create_caregiver"),
                  path('create_participante/<str:grupo_id>', views.create_participante, name="create_participante"),
                  path('create_mentor/<str:grupo_id>', views.create_mentor, name="create_mentor"),
                  path('create_colaborador', views.create_colaborador, name="create_colaborador"),
                  path('grupo_details/<int:grupo_id>', views.view_group_details, name="grupo_details"),
                  path('delete_groups/<str:grupo_id>', views.delete_groups, name='delete_grupos'),
                  path('update_groups/<str:grupo_id>', views.update_groups, name="update_groups"),
                  path('filter_group/<int:cuidador_id>', views.filter_group, name='filter_group'),
                  path('new_group', views.new_group, name="new_group"),
                  path('assign_group/<int:grupo_id>/<int:cuidador_id>', views.assign_group, name='assign_group'),
                  path('guarda_grupo', views.guarda_grupo, name="guarda_grupo"),
                  path('group_members/<int:grupo_id>', views.group_members, name='group_members'),
                  path('group_sessions/<int:grupo_id>', views.group_sessions, name='group_sessions'),
                  path('group_notes/<int:grupo_id>', views.group_notes, name='group_notes'),
                  path('create_dinamizador/<str:grupo_id>', views.create_dinamizador, name="create_dinamizador"),
                  path('colaborador_update/<str:colaborador_id>', views.colaborador_update,
                       name='colaborador_update'),
                  path('dinamizador_update/<str:dinamizador_id>/<str:grupo_id>', views.dinamizador_update,
                       name='dinamizador_update'),
                  path('mentor_update/<str:mentor_id>/<str:grupo_id>', views.mentor_update,
                       name='mentor_update'),
                  path('dinamizador_delete/<str:dinamizador_id>/<str:grupo_id>', views.dinamizador_delete,
                       name='dinamizador_delete'),
                  path('caregiver_update/<str:cuidador_id>/<str:grupo_id>', views.caregiver_update,
                       name='caregiver_update'),
                  path('participante_update/<str:participante_id>/<str:grupo_id>', views.participante_update,
                       name='participante_update'),
                  path('caregiver_delete/<str:cuidador_id>/<str:grupo_id>', views.caregiver_delete,
                       name='caregiver_delete'),
                  path('assign_dinamizador/<int:grupo_id>/<int:dinamizador_id>', views.assign_dinamizador,
                       name='assign_dinamizador'),
                  path('assign_mentor/<int:grupo_id>/<int:mentor_id>', views.assign_mentor,
                       name='assign_mentor'),
                  path('assign_participante/<int:grupo_id>/<int:participante_id>', views.assign_participante,
                       name='assign_participante'),
                  path('assign_caregiver/<int:grupo_id>/<int:cuidador_id>', views.assign_caregiver,
                       name='assign_caregiver'),
                  path('diario/<int:idGrupo>/<int:idSessao>', views.view_diario, name='diario'),
                  path('diario_participante/<int:idSessaoGrupo>/<int:idParticipante>', views.view_diario_participante,
                       name='diario_participante'),
                  path('diario_grupo/<int:idSessaoGrupo>', views.view_diario_grupo, name='diario_grupo'),
                  path('atualizaPresencasDiario/<int:idSessaoGrupo>', views.view_atualiza_presencas_diario,
                       name='atualiza_presencas_diario'),
                  path('questionario_satisfacao/<int:idPergunta>/<int:idParte>/<int:sessaoGrupo>',
                       views.view_questionario_satisfacao,
                       name="questionario_satisfacao"),
                  path('questionario/<int:idPergunta>/<int:idParte>/<int:sessaoGrupo>', views.view_questionario,
                       name="view_questionario"),
                  path('exercicio/<int:idExercicio>/<int:parteGrupo>/<int:sessaoGrupo>', views.view_exercicio,
                       name="exercicio"),
                  path('abrirQuestionario/<int:idPergunta>/<int:idParte>/<int:sessaoGrupo>',
                       views.view_abrirQuestionario,
                       name="view_abrirQuestionario"),
                  path('resultados/<int:idPergunta>/<int:idParte>/<int:sessaoGrupo>', views.view_resultados,
                       name='resultados'),
                  path('parte/<int:parte_do_grupo_id>/<int:sessaoGrupo_id>/<str:estado>/<int:proxima_parte>',
                       views.view_parte, name="parte"),
                  path('parteDetalhes/<int:parte_do_grupo_id>/<int:sessaoGrupo_id>/<int:idGrupo>',
                       views.view_parteDetalhes,
                       name="parteDetalhes"),
                  path('finalizar_parte/<int:idParte>/<int:sessao_grupo_id>/<str:estado>', views.finalizar_parte,
                       name='finalizar_parte'),
                  path('finalizar_sessao/<int:idGrupo>/<int:sessao_grupo_id>', views.finalizar_sessao,
                       name='finalizar_sessao'),
                  path('iniciar_sessao/<int:sessao_grupo_id>', views.view_iniciar_sessao, name='iniciar_sessao'),
                  path('changeDate/<int:sessao_id>/<int:group_id>', views.view_changeDate, name='changeDate'),
                  path('sessao/<int:sessao_grupo_id>/<int:grupo_id>', views.view_sessao, name='sessao'),
                  path('presencas_sessao/<int:proxima_id>', views.view_presencas_sessao, name='presencas_sessao'),
                  path('voltar_parte/<int:idParte>/<int:sessao_grupo_id>/<str:estado>', views.voltar_parte,
                       name='voltar_parte'),
                  path('partilha_parte/<int:sessaoGrupo>/<int:idParteExercico>', views.partilha_parte,
                       name='partilha_parte'),
                  path(
                      'guarda_resposta/<int:sessaoGrupo_id>/<int:parteGrupo_id>/<int:utilizador_id>/<int:pergunta_id>/<int:parte_exercicio_id>',
                      views.guarda_resposta_view, name="guarda_resposta"),
                  path('avaliacao_participantes/<int:sessaoGrupoid>', views.view_avaliacao_participantes,
                       name="avaliacao_participantes"),
                  #    path('respostas/<int:idSessaoGrupo>/<int:idParticipante>/', views.respostas_view,
                  #         name="respostas"),
                  path('guarda_avaliacao_participante/<int:sessaoGrupo_id>', views.guarda_avaliacao_participante,
                       name="guarda_avaliacao_participante"),
                  path('guarda_avaliacao_sessao/<int:sessaoGrupo_id>', views.guarda_avaliacao_sessao,
                       name="guarda_avaliacao_participante"),
                  path('obter_candidatos', views.obter_cadidatos, name="obter_candidatos"),
                  path('parte_ativa/<int:sg_id>', views.parte_ativa, name="parte_ativa"),
                  path('user_dashboard', views.user_dashboard, name="user_dashboard"),
                  path('streamss/', views.streams, name="streams"),
                  path('get_token/', views.getToken, name="get_token"),
                  path('complete_partilha/<int:partilha_id>/', views.complete_partilha, name='complete_partilha'),
                  path('remove_partilha/<int:partilha_id>/', views.remove_partilha, name='remove_partilha'),
                  path('colaboradores', views.colaboradores, name='colaboradores'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diario/templates/diario/filtrar_grupo_para_candidato.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,700,1,0" />
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <style>

    @media (min-width: 1000px) {
            div.center {
                width: 100vw;
            }
        }
    .dashboard > div {
            padding-left: 50px;
            padding-right: 50px;
            padding-top: 20px;
            padding-bottom: 10px;
            margin: 20px;
            font-size: 1em;
            border-radius: 10px;
            border: 0px;
            background-color: whitesmoke;
            box-shadow: -5px -5px 9px rgba(255,255,255,0.45), 5px 5px 9px rgba(94,104,121,0.3);
        }
         .dashboard .title {
             grid-area: title;
             background-color: #4EB4BE;
             color: whitesmoke;
             text-align: center;

        }
          h1{
            margin-top: auto;
            margin-bottom: auto;
            margin-right: auto;
            margin-left: auto;
            font-size: 25px;
        }
           .dashboard .info {
            grid-area: info;
            background-color: #4EB4BE;
             text-align: center;

        }
           button, form {
               margin: auto;
            display: inline;
               border-radius: 5px;

        }
           table table-hover {
      width: 84%;
      position: absolute;
      right: 10px;
    }
           .button3 {

            background-color: #4EB4BE;
            border: none;
            color: white;
            margin: auto;
        }
           .info_btn{
        display: inline-block;
        padding: 5px;
        width: 200px;
        height: auto;
        background-color: #4EB4BE;
        border: 1px;
        color: white;
        margin: 0 60px;
    }
    </style>
</head>

    <body>
        <div class="center">
            <div class="container">
                <div class="dashboard">
                    <div class="info">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Cuidador Sem Grupo</th>
                                    <th>Localização</th>
                                    <th>Escolaridade</th>
                                    <th>Referenciação</th>
                                </tr>
                            </thead>
                            <tbody>
                                 <tr>
                                    <td>{{ cuidador }}</td>
                                    <td>{{ cuidador.localizacao }}</td>
                                    <td>{{ cuidador.escolaridade }}</td>
                                    <td>{{ cuidador.referenciacao }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="center">
            <div class="container">
                <div class="dashboard">
                    <div class="title">
                        <h1>Filtros para Grupos</h1>
                    </div>
                    <div class="info">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Cuidador Sem Grupo</th>
                                    <th>Diagnóstico </th>
                                    <th>Localização</th>
                                    <th>Escolaridade</th>
                                    <th>Referenciação</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <input form="filtro" type="submit" value="Filtrar">
                                    </td>
                                    <form id="filtro" action="{% url 'diario:filtrar_grupo_para_candidato' cuidador.id %}" method="POST">
                                        {% csrf_token %}
                                        {% for campo,opcoes in lista_pesquisa.items %}
                                        <td class="opcao">
                                            <select name="{{campo}}" id="">
                                                <option value=""></option>
                                                {% for opcao in opcoes %}
                                                    <option value="{{ opcao }}">{{ opcao }}</option>
                                                {% endfor %}
                                            </select>
                                        </td>
                                    {% endfor %}
                                </form>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
     </div>

        <div class="center">
            <div class="container">
                <div class="dashboard">
                    <div class="title">
                        <h1>Resultados dos Grupos</h1>
                    </div>
                    <div class="info">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Cuidador Sem Grupo</th>
                                    <th>Diagnóstico </th>
                                    <th>Localização</th>
                                    <th>Escolaridade</th>
                                    <th>Referenciação</th>
                                    <th>Nº Membros</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for grupo in grupos %}
                                <tr>
                                    <td>
                                        <form action="{% url 'diario:grupo' grupo.id %}">
                                            <button type="submit">{{ grupo }}</button>
                                        </form>
                                    </td>
                                    <td>{{ grupo.diagnostico }}</td>
                                    <td>{{ grupo.localizacao }}</td>
                                    <td>{{ grupo.escolaridade }}</td>
                                    <td>{{ grupo.referenciacao }}</td>
                                    <td>{{ grupo.cuidadores.all|length }}</td>
                                    <td>
                                        <form action="{% url 'diario:atribui_grupo' grupo.id cuidador.id %}" method="POST">
                                            {% csrf_token %}
                                            <button class="button3">Inscrever</button>
                                        </form>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
                <form  action="{% url 'diario:grupos' %}">
                    <button type="submit" class='info_btn'>Voltar</button>
                </form>
            </div>
        </div>
    </body>
</html>


diario/templates/diario/group_notes.html
{% extends 'diario/base.html' %}
{% load static %}
{% block main %}
<div class="container-fluid">
    <div class="container text-start">
        <div class="row">
            <div class="col align-self-center">
                <div class="titulo" style="display: flex;flex-direction: row;justify-content: space-between">
                    <div class="card-body" style="padding: 8px">
                        <p class="text-primary m-0 fw-bold"
                            style="margin: 5px; font-size: 26px">Sessões do
                            Grupo {{ grupo }}</p>
                    </div>
                    <div>
                        <form action="{% url 'diario:grupo_details' grupo.id %}">
                            <button type="submit" class="btn btn-outline-primary" style="width: 150px">
                                Anterior
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container ">
        <div class="card shadow">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th style="text-align: center;"><strong>Sessão</strong></th>
                            <th style="text-align: center;"><strong>Data e hora</strong></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for detalhe in sessoes %}
                        <tr>
                            <td style="text-align: center;">Sessão {{ detalhe.numeroSessao }}</td>
                            <td style="text-align: center;">{{ detalhe.data }}</td>
                            <td style="text-align: center;">

                                <button class="btn btn-primary " type="button" style="border-radius: 8px"
                                        data-bs-toggle="modal" data-bs-target="#Visualizar">
                                    Visualizar
                                </button>

                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- The Modal  Cuidador sem grupo -->
<div class="modal" id="Visualizar">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Notas</h4>
            </div>
            <!-- Modal body -->
            <div class="modal-body">
                {% for notas in notasGrupo %}
                <p>{{notas}}</p>
                {% endfor %}
            </div>
            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>

{% endblock %}

diario/templates/diario/mentor_update.html
{% extends 'diario/base.html' %}
{% load static %}
{% block main %}
    <div id="wrapper">
        <div class="d-flex flex-column" id="content-wrapper">
            <div id="content">
                <div class="d-sm-flex justify-content-between align-items-center mb-4">
                </div>
                <div class="container-fluid">
                    <div class="d-sm-flex justify-content-between align-items-center mb-4"></div>
                    <div class="d-sm-flex justify-content-between align-items-center mb-4"></div>
                    <div class="d-sm-flex justify-content-between align-items-center mb-4"></div>
                    <div class="d-sm-flex justify-content-between align-items-center mb-4"></div>
                    <div class="container text-start">
                        <div class="row">
                            <div class="col align-self-center">
                                <div style="display: flex;flex-direction: row;justify-content: space-between">
                                    <div class="card-body" style="padding: 8px">
                                        <p class="m-0 fw-bold" style="margin: 5px; font-size: 26px; color: #4EB4BE">
                                            Editar Mentor</p>
                                        <br>
                                        {% if error_message %}
                                            <p class="m-0 fw-bold fs-5">{{ error_message }}</p>
                                        {% endif %}
                                    </div>
                                    <div>
                                        <form action="{% url 'diario:group_members' grupo_id %}">
                                            <button type="submit" class="btn mb-btn-outline" style="width: 150px">
                                                <i class="fa-solid fa-angle-left"></i> Anterior
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="d-sm-flex justify-content-between align-items-center mb-4"></div>
                    <div class="container text-start">
                        <div class="row">
                            <div class="col align-self-center">
                                <div class="card shadow">
                                    <div class="card-body">
                                        <div class="row">
                                            <form action="" class="row g-3" method="post" enctype="multipart/form-data">
                                                {% csrf_token %}
                                                <div style="display: flex;gap: 8px">
                                                    <div class="fieldWrapper" style="width: 70%">
                                                        <label for="{{ formMentor.nome.id_for_label }}">{{ formMentor.nome.label }}: </label>
                                                        <input type="text" id="{{ formMentor.nome.id_for_label }}"
                                                               name="{{ formMentor.nome.html_name }}"
                                                               value="{{ mentor.nome }}">
                                                    </div>
                                                    <div class="fieldWrapper" style="width: 30%">
                                                        <label for="{{ formMentor.sexo.id_for_label }}">{{ formMentor.sexo.label }}: </label>
                                                        {{ formMentor.sexo }}
                                                    </div>
                                                </div>
                                                <div style="display: flex; gap: 8px">
                                                    <div class="fieldWrapper" style="width: 100%">
                                                        <label for="{{ formMentor.username.id_for_label }}">{{ formMentor.username.label }}: </label>
                                                        <input type="text" id="{{ formMentor.username.id_for_label }}"
                                                               name="{{ formMentor.username.html_name }}"
                                                               value="{{ mentor.user.username }}">
                                                    </div>
                                                    </div>

                                                    <input type="hidden" name="password" value="@MentHA@23" id="id_password">
                                                </div>
                                                <div class="fieldWrapper" style="width: 100%">
                                                    <label for="{{ formMentor.email.id_for_label }}">{{ formMentor.email.label }}: </label>
                                                    <input type="text"
                                                           id="{{ formMentor.email.id_for_label }}"
                                                           name="{{ formMentor.email.html_name }}"
                                                           value="{{ mentor.email }}">
                                                </div>
                                                <div style="display: flex; gap: 8px">
                                                    <div class="fieldWrapper" style="width: 50%">
                                                        <label for="{{ formMentor.nacionalidade.id_for_label }}">{{ formMentor.nacionalidade.label }}: </label>
                                                        <input type="text"
                                                               id="{{ formMentor.nacionalidade.id_for_label }}"
                                                               name="{{ formMentor.nacionalidade.html_name }}"
                                                               value="{{ mentor.nacionalidade }}">
                                                    </div>
                                                    <div class="fieldWrapper" style="width: 50%">
                                                        <label for="{{ formMentor.telemovel.id_for_label }}">{{ formMentor.telemovel.label }}: </label>
                                                        <input type="text"
                                                               id="{{ formMentor.telemovel.id_for_label }}"
                                                               name="{{ formMentor.telemovel.html_name }}"
                                                               value="{{ mentor.telemovel }}">
                                                    </div>
                                                </div>
                                                <div style="display: flex; gap: 8px">
                                                    <div class="fieldWrapper" style="width: 50%">
                                                        <label for="{{ formMentor.localizacao.id_for_label }}">{{ formMentor.localizacao.label }}: </label>
                                                        <input type="text"
                                                               id="{{ formMentor.localizacao.id_for_label }}"
                                                               name="{{ formMentor.localizacao.html_name }}"
                                                               value="{{ mentor.localizacao }}">
                                                    </div>
                                                    <div class="fieldWrapper" style="width: 50%">
                                                        <label for="{{ formMentor.nascimento.id_for_label }}">{{ formMentor.nascimento.label }}: </label>
                                                        {{ formMentor.nascimento }}
                                                    </div>
                                                </div>
                                                <div style="display: flex; flex-direction: row; justify-content: flex-start">
                                                    <div class="col-md-6">
                                                        <button type="submit" class="btn mb-btn-outline"
                                                                style="width: 150px; color: white">
                                                            <i class="fa fa-floppy-disk"></i> Editar
                                                        </button>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="d-sm-flex justify-content-between align-items-center mb-4"></div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

diario/templates/diario/menu_esquerda.html
<style>
.linha-vertical {
  color: #4EB4BE;

 width: 50%;
 float: left;
  padding: 15px;
  margin: 10px;
  position: relative;
  margin-left: 120px;
  height: 100%;/*Altura da linha*/
  border-left: 2px solid;/* Adiciona borda esquerda na div como ser fosse uma linha.*/
  box-sizing: border-box;
}
.opcaoMenu1 {
  position: absolute;
  margin-left: 20px;
  margin-top: 200px;
  text-align: center;
  font-size: 20px;
  color:black;

}
.opcaoMenu2 {
  width: 15px;
  position: absolute;
  margin-left: 20px;
  margin-top: 250px;
  text-align: center;
  font-size: 20px;
  color:black;
}
.opcaoMenu3 {
  position: absolute;
  margin-left: 20px;
  margin-top: 330px;
  text-align: center;
  font-size: 20px;
  color:black;
}
.opcaoMenu4 {

}

a:link {
  text-decoration: none;
}


</style>

<body>
<div class="opcaoMenu1">
    <a style="color:black">
      Home
    </a>
</div>
<div class="opcaoMenu2">
    <a style="color:black" >
        Pagina Principal
    </a>
</div>
<div class="opcaoMenu3">
    <a style="color:black" >
        Calendario
    </a>
</div>
<div class="linha-vertical">

</div>

</body>
</html>

diario/templates/diario/sessoes_grupo.html
<h3>Sessões do Grupo {{ grupo }} </h3>